@startuml "Single Commands"

title "Single Command CLIENT_SERVER Miss Ack"
!pragma teoz true

participant client
participant server

client -> server: Request [ID=01, PRIORITY=APP, COMMAND]

server -> server: Process [ID=01, PRIORITY=USER, COMMAND]
{start1} server -> client: Send [ID=01, Response]
client -> client: Process Response

{end1} server -> server: timeout with no ACK
server -> client: Resend [ID=01, Response]
client -> server: OK ID=01

{start1} <-> {end1}: timer 1
@enduml