@startuml "Single Commands"

title "Single Command CLIENT_SERVER Corrupted Response"
!pragma teoz true

participant client
participant server

client -> server: Request [ID=01, PRIORITY=APP, COMMAND]

server -> server: Process [ID=01, PRIORITY=USER, COMMAND]
server -> client: Send [ID=01, Response]
client -> client: Process Response
client -> client: Corrupted Response
client -> server: Request Resend 01

server -> client: Resend [ID=01, Response]
client -> server: OK ID=01

@enduml